# Generated by Django 3.1.10 on 2023-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
