# Generated by Django 3.1.10 on 2023-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='Link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='Link2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='Link3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='Linkname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='Linkname2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='Linkname3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
