# Generated by Django 3.1.10 on 2023-10-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20231018_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='Image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='Image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='Image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='Image5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='Image6',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cat',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
