# Generated by Django 3.1.10 on 2023-11-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20231018_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='shotnot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='shotnot2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='shotnot3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
